### ISSUE TITLE
Divide the document in multiple tex files

### ISSUE THREAD

**Issue by valvy** [SoftwareForScience/SRS_Bookkeeping#1]
# Introduction
Latex supports with the syntax \input and \include the ability to divide itself in multiple files.
For optimal use of Git and allowing more than one person to work on the documents without merge conflicts. 

A rule should be thought out how to divide the tex files. Into chapters or sections.

**Comment by MartenTeitsma** [comment]
The SRS is divided in three files according to the chapters of IEEE standard 830-1998.
